apiVersion: v1
kind: Service
metadata:
  name: vote-np
spec:
  selector:
    app: vote             # Select all Pods having label 'app' with value 'vote'
  type: NodePort          # FROM OUTSIDE THE CLUSTER VIA nodePort (below)
  ports:
    - port: 80            # Arrive at port 80 of the service
      targetPort: 80      # Forwarded on the port 80 of a Pod
      nodePort: 31000     # EXPOSED PORT
