apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREakNDQWZhZ0F3SUJBZ0lUY3A5UHZVZkNXc2JNeU1IVmVWRDIwVGVhb0RBTkJna3Foa2lHOXcwQkFRc0YKQURBWE1SVXdFd1lEVlFRRERBd3hNQzR4TlRJdU1UZ3pMakV3SGhjTk1qSXhNREEwTVRVek1UVTRXaGNOTXpJeApNREF4TVRVek1UVTRXakFYTVJVd0V3WURWUVFEREF3eE1DNHhOVEl1TVRnekxqRXdnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREpJM1pQLzdkN2YvT0NFbnNUMTlvNjMrNytHdVh3WDRRMVJKdWIKVTFVQWlMZU9XWVFzTTc5L3lRNXl3WFVkNlg3UFRKSkJGYjFVaURzcGZvK01UN3VMQUJWckowaG9XNUl3cUozZAptUG5NeFd3UVZWb0tVWFA3ZHNxVXhVczdXRy9ra0dJS0Y1YzM0QjBMUDdLOWxyNGZLbUd3bXA4cnJ2cmtpdFcrCkQ0QmZkQS9MREViS2htOW5VSWRIay9Ja0lnYTlNL2huOTVqb0VZUWFtUDgrVWIrSlg0KzR5WGozN2JDNmw0NlIKRk5ockxHUDUvNG9vUWFUWkZBSklhZ0VNakVIcFlFVFhzVW5lbVA4dVd2b3kraFdGR1BkNUc5Sm15b2xrK3VWawpGcjFlYThpZm1jWEF1c1QyNTlLckh2dnhHNkQ0dVoydjd5bXI1cWxYQ1pRVU1vdTNBZ01CQUFHalV6QlJNQjBHCkExVWREZ1FXQkJRYndzQVJybWFnZXZkZnAzbDlhL01SbWI3S3VqQWZCZ05WSFNNRUdEQVdnQlFid3NBUnJtYWcKZXZkZnAzbDlhL01SbWI3S3VqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUFGYmloVThvd0FYTjJPdm9aUFk1aVAyRTRjRGtYeHNOOXBKQ0JFRnNLNEJBUGYzclhYYWZMZDNCMjFBZ21lCjhTSFQvVFc1VlhRNkgycS9HWTNYMml2TXVPUHp2enlKd2lwM2lWaUdyMnJZMkQ1TE82RWxiKzJqZi9lbnF1Y2wKMkxYLyt5SStLOWJ6U2tyTVgxdHZzUDFvR2RnTDdGOGJVT2FTUmV3Y2Y5Z1FQMVA3RFVaRDBqUFVJMjR4eVVSdQpoZW1GcHhoZ3FPNldmdDZ5UnZ0Z01uWkEzdExRcmNzTC91bXNEZGtqT29xWkk2bmdObTZSd0hvOWNBMisyckE3Cm9WVXZtd0l2Q3lUVm5UOU1mcEloOHNsQ2tIMkh5MUZsN0U5aG1ublUvNmxhcWRXS2xLQWxQQjFha0Jyd3BwenQKRGZVZGppQkN1blJUM29wUEdRL293UklmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.64.7:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eUtnSFlobXJMUnFNWm1yS25abUhMc3JtY0hwMEFWbDF0cFZlaG1WRlN5MD0K

